import type { Language } from '../types'

type Dictionary = Record<string, string>

const en: Dictionary = {
  appName: 'My Trading Agent', tagline: 'LOCAL AI. SMARTER TRADING.', localMode: 'Local Mode', localModeSub: 'All data stays on your machine',
  ollamaConnected: 'Ollama Connected', paperTrading: 'Paper Trading', simulatedExecution: 'Simulated execution', emergencyStop: 'EMERGENCY STOP', emergencyActive: 'STOPPED',
  language: 'PT', simulation: 'DEMO / SIMULATION', activeAgents: 'agents active', officeTitle: 'Trading Agent Pixel Office', officeSubtitle: 'Specialized agents working together 24/7',
  dashboard:'Dashboard', markets:'Markets', charts:'Charts', aiAnalyst:'AI Analyst', agentOffice:'Agent Office', scanner:'Scanner', portfolio:'My Portfolio', strategies:'Strategies', backtesting:'Backtesting', liveTrading:'Live Trading', tradeJournal:'Trade Journal', alerts:'Alerts', exchangeConnections:'Exchange Connections', ollamaModels:'Ollama Models', settings:'Settings', planned:'PLANNED',
  marketAnalyst:'Market Analyst', riskManager:'Risk Manager', strategyResearcher:'Strategy Researcher', sentimentAnalyst:'Sentiment Analyst', tradeCritic:'Trade Critic', portfolioManager:'Portfolio Manager', finalDecisionAgent:'Final Decision Agent', backtestingLab:'Backtesting Lab', paperTrader:'Paper Trader', executionAgent:'Execution Agent', agentManager:'Agent Manager',
  marketRoom:'Market Analysis Room', riskRoom:'Risk Management Room', strategyRoom:'Strategy Lab', sentimentRoom:'Sentiment Desk', criticRoom:'Trade Critic Desk', portfolioRoom:'Portfolio Room', decisionRoom:'Final Decision Room', backtestingRoom:'Backtesting Lab', paperRoom:'Paper Trading Area', executionRoom:'Execution Desk', managerRoom:'Manager / Control Room',
  analyzeBtc:'Analyzing BTC-USD', checkSize:'Checking position size', testIdea:'Testing new idea', scanSentiment:'Scanning market sentiment', reviewTrade:'Reviewing proposed trade', checkExposure:'Checking exposure', compareReports:'Comparing agent reports', runBacktest:'Running strategy test', simulateExecution:'Simulating execution', readyOrders:'Ready for paper orders', systemNormal:'System running normally',
  marketDetail:'BTC is holding above short-term support while volume and momentum are being checked across multiple timeframes.', riskDetail:'Validating position size, stop distance, drawdown rules, portfolio exposure and hard loss limits.', strategyDetail:'Testing whether the current setup meets enabled strategy rules before it can become a candidate.', sentimentDetail:'Reviewing free market/news signals and rejecting low-confidence or stale information.', criticDetail:'Actively searching for reasons this setup could fail before it is allowed to move forward.', portfolioDetail:'Checking concentration, correlated exposure, available capital and existing open positions.', decisionDetail:'Combining structured reports. A WAIT decision is valid when evidence is incomplete.', backtestDetail:'Testing the candidate against historical candles with fees and slippage assumptions.', paperDetail:'Simulating the setup without real money before any live-trading eligibility is considered.', executionDetail:'Execution remains locked to paper mode in this frontend phase.', managerDetail:'Watching agent health, stale data flags, failures and the emergency-stop state.',
  lastMarket:'Updated support/resistance levels', lastRisk:'Blocked an oversized position', lastStrategy:'Completed BTC trend filter', lastSentiment:'Updated sentiment confidence', lastCritic:'Rejected weak SOL setup', lastPortfolio:'Updated exposure map', lastDecision:'Returned WAIT on BTC-USD', lastBacktest:'Completed MA crossover test', lastPaper:'Opened ETH paper trade', lastExecution:'Synced paper order book', lastManager:'Checked agent heartbeat',
  working:'Working', reviewing:'Reviewing', waiting:'Waiting', approved:'Approved', idle:'Idle',
  agentDetails:'Agent Details', currentTask:'Current task', currentStatus:'Current status', lastCompleted:'Last completed', reasoning:'Reasoning', timeStarted:'Time started', ollamaProcessing:'Ollama processing', yes:'Yes', no:'No',
  terminal:'Pro Trading Terminal', watchlist:'Watchlist', orderBook:'Order Book', recentTrades:'Recent Trades', riskSummary:'Signal & Risk Summary', trend:'Trend', bullish:'Bullish', momentum:'Momentum', positive:'Positive', volatility:'Volatility', moderate:'Moderate', liquidity:'Liquidity', high:'High', riskReward:'Risk / Reward', exposure:'Current Exposure', aiDecision:'AI Decision', wait:'WAIT',
  activity:'Live Activity Feed', activePaper:'Active Paper Trades', decisionFlow:'AI Decision Flow', backtestResults:'Strategy Backtest Results', journal:'Journal / Recent Decisions',
  data:'Data', analysis:'Analysis', signal:'Signal', risk:'Risk', paperTrade:'Paper Trade', approval:'Approval',
  makeMoneyRule:'Protect capital first. Every trade must earn the right to exist.', localPrivate:'Local • Private • Modular', systemsOperational:'Local server connected', serverConnected:'Server Connected', serverOffline:'Server Offline', startBatHint:'Run START.bat', ollamaOffline:'Ollama Offline', coinbaseReady:'Coinbase Ready', coinbaseLive:'COINBASE LIVE', demoData:'DEMO DATA', liveBackend:'LIVE BACKEND',
  clickAgent:'Click any agent room to inspect what that agent is doing.', mobileHint:'Swipe sideways inside dense terminal tables if needed.'
}

const pt: Dictionary = {
  appName:'My Trading Agent', tagline:'IA LOCAL. TRADING MAIS INTELIGENTE.', localMode:'Modo Local', localModeSub:'Seus dados ficam na sua máquina', ollamaConnected:'Ollama Conectado', paperTrading:'Paper Trading', simulatedExecution:'Execução simulada', emergencyStop:'PARADA DE EMERGÊNCIA', emergencyActive:'PARADO', language:'EN', simulation:'DEMO / SIMULAÇÃO', activeAgents:'agentes ativos', officeTitle:'Escritório Pixel dos Agentes', officeSubtitle:'Agentes especializados trabalhando juntos 24/7',
  dashboard:'Painel', markets:'Mercados', charts:'Gráficos', aiAnalyst:'Analista IA', agentOffice:'Escritório dos Agentes', scanner:'Scanner', portfolio:'Meu Portfólio', strategies:'Estratégias', backtesting:'Backtesting', liveTrading:'Trading Real', tradeJournal:'Diário de Trades', alerts:'Alertas', exchangeConnections:'Conexões de Exchange', ollamaModels:'Modelos Ollama', settings:'Configurações', planned:'PLANEJADO',
  marketAnalyst:'Analista de Mercado', riskManager:'Gerente de Risco', strategyResearcher:'Pesquisador de Estratégia', sentimentAnalyst:'Analista de Sentimento', tradeCritic:'Crítico de Trades', portfolioManager:'Gerente de Portfólio', finalDecisionAgent:'Agente de Decisão Final', backtestingLab:'Laboratório de Backtest', paperTrader:'Paper Trader', executionAgent:'Agente de Execução', agentManager:'Gerente dos Agentes',
  marketRoom:'Sala de Análise de Mercado', riskRoom:'Sala de Gestão de Risco', strategyRoom:'Laboratório de Estratégia', sentimentRoom:'Mesa de Sentimento', criticRoom:'Mesa do Crítico de Trades', portfolioRoom:'Sala de Portfólio', decisionRoom:'Sala de Decisão Final', backtestingRoom:'Laboratório de Backtesting', paperRoom:'Área de Paper Trading', executionRoom:'Mesa de Execução', managerRoom:'Sala de Controle / Gerente',
  analyzeBtc:'Analisando BTC-USD', checkSize:'Verificando tamanho da posição', testIdea:'Testando nova ideia', scanSentiment:'Analisando sentimento do mercado', reviewTrade:'Revisando trade proposto', checkExposure:'Verificando exposição', compareReports:'Comparando relatórios dos agentes', runBacktest:'Executando teste de estratégia', simulateExecution:'Simulando execução', readyOrders:'Pronto para ordens simuladas', systemNormal:'Sistema funcionando normalmente',
  marketDetail:'BTC está acima do suporte de curto prazo enquanto volume e momentum são verificados em vários períodos.', riskDetail:'Validando tamanho da posição, distância do stop, drawdown, exposição do portfólio e limites rígidos de perda.', strategyDetail:'Testando se o setup atual atende às regras das estratégias habilitadas antes de virar candidato.', sentimentDetail:'Revisando sinais gratuitos de mercado/notícias e rejeitando informação fraca ou desatualizada.', criticDetail:'Procurando ativamente motivos para este setup falhar antes de permitir que avance.', portfolioDetail:'Verificando concentração, correlação, capital disponível e posições já abertas.', decisionDetail:'Combinando relatórios estruturados. WAIT é uma decisão válida quando faltam evidências.', backtestDetail:'Testando o candidato em candles históricos incluindo taxas e premissas de slippage.', paperDetail:'Simulando o setup sem dinheiro real antes de considerar qualquer elegibilidade para trading real.', executionDetail:'A execução continua travada no modo paper nesta fase do frontend.', managerDetail:'Monitorando saúde dos agentes, dados desatualizados, falhas e a parada de emergência.',
  lastMarket:'Atualizou suporte e resistência', lastRisk:'Bloqueou uma posição grande demais', lastStrategy:'Concluiu filtro de tendência do BTC', lastSentiment:'Atualizou confiança do sentimento', lastCritic:'Rejeitou setup fraco de SOL', lastPortfolio:'Atualizou mapa de exposição', lastDecision:'Retornou WAIT no BTC-USD', lastBacktest:'Concluiu teste de cruzamento de médias', lastPaper:'Abriu paper trade de ETH', lastExecution:'Sincronizou book simulado', lastManager:'Verificou heartbeat dos agentes',
  working:'Trabalhando', reviewing:'Revisando', waiting:'Aguardando', approved:'Aprovado', idle:'Ocioso',
  agentDetails:'Detalhes do Agente', currentTask:'Tarefa atual', currentStatus:'Status atual', lastCompleted:'Última tarefa concluída', reasoning:'Resumo do raciocínio', timeStarted:'Início da tarefa', ollamaProcessing:'Ollama processando', yes:'Sim', no:'Não',
  terminal:'Terminal Profissional', watchlist:'Lista de Monitoramento', orderBook:'Livro de Ofertas', recentTrades:'Trades Recentes', riskSummary:'Resumo de Sinal e Risco', trend:'Tendência', bullish:'Altista', momentum:'Momentum', positive:'Positivo', volatility:'Volatilidade', moderate:'Moderada', liquidity:'Liquidez', high:'Alta', riskReward:'Risco / Retorno', exposure:'Exposição Atual', aiDecision:'Decisão da IA', wait:'AGUARDAR',
  activity:'Feed de Atividade', activePaper:'Paper Trades Ativos', decisionFlow:'Fluxo de Decisão da IA', backtestResults:'Resultados de Backtest', journal:'Diário / Decisões Recentes',
  data:'Dados', analysis:'Análise', signal:'Sinal', risk:'Risco', paperTrade:'Paper Trade', approval:'Aprovação',
  makeMoneyRule:'Proteja o capital primeiro. Todo trade precisa merecer existir.', localPrivate:'Local • Privado • Modular', systemsOperational:'Servidor local conectado', serverConnected:'Servidor Conectado', serverOffline:'Servidor Offline', startBatHint:'Execute START.bat', ollamaOffline:'Ollama Offline', coinbaseReady:'Coinbase Pronta', coinbaseLive:'COINBASE AO VIVO', demoData:'DADOS DEMO', liveBackend:'BACKEND AO VIVO',
  clickAgent:'Clique em qualquer sala para ver o que o agente está fazendo.', mobileHint:'Em telas menores, deslize as tabelas do terminal para o lado se precisar.'
}

export const dictionaries: Record<Language, Dictionary> = { en, pt }
