import { useEffect,useState } from 'react'
import { activities as demoActivities } from '../data/demo'
import { api } from '../lib/api'
interface Props {t:(key:string)=>string;backendOnline:boolean}
export function BottomPanels({t,backendOnline}:Props){
 const [liveEvents,setLiveEvents]=useState<any[]>([])
 useEffect(()=>{if(!backendOnline)return;api.getRecentEvents().then(r=>setLiveEvents(r.events.slice(0,6))).catch(()=>{});const es=new EventSource(api.eventUrl,{withCredentials:true});es.addEventListener('agent',(event:any)=>{try{const row=JSON.parse(event.data);setLiveEvents(prev=>[row,...prev].slice(0,6))}catch{}});return()=>es.close()},[backendOnline])
 const rows=liveEvents.length?liveEvents.map(event=>[new Date(event.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),event.agentId||'System',event.type.replaceAll('_',' '),event.type.includes('rejected')||event.type.includes('emergency')?'warn':'ok']):demoActivities
 return <div className="bottom-panels"><section className="panel compact-panel"><header className="mini-heading"><h3>{t('activity')}</h3><span>● {backendOnline?t('liveBackend'):'DEMO'}</span></header><div className="activity-list">{rows.map(([time,agent,event,status]:any,i:number)=><div className="activity-row" key={String(time)+String(agent)+i}><i className={status==='ok'?'ok':'warn'}/><time>{time}</time><strong>{agent}</strong><span>{event}</span></div>)}</div></section><section className="panel compact-panel"><header className="mini-heading"><h3>{t('decisionFlow')}</h3></header><div className="flow">{['data','analysis','signal','risk','backtesting','paperTrade','approval'].map((k,i)=><div className={`flow-step ${i<6?'done':''}`} key={k}><b>{i<6?'✓':'○'}</b><span>{t(k)}</span></div>)}</div><div className="paper-summary"><div><small>ETH-USD</small><strong>+0.05%</strong></div><div><small>SOL-USD</small><strong>+0.72%</strong></div><div><small>ADA-USD</small><strong>+0.64%</strong></div></div></section><section className="panel compact-panel"><header className="mini-heading"><h3>{t('backtestResults')}</h3></header><div className="backtest-table"><div><strong>MA Crossover</strong><span>68.4%</span><em>+142.7%</em></div><div><strong>RSI Mean Rev.</strong><span>62.1%</span><em>+87.3%</em></div><div><strong>Bollinger</strong><span>56.8%</span><em>+61.2%</em></div></div></section></div>
}
